name: Build and Test

on:
  push:
    branches: [ dev ]

jobs:
  lighthouse-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse

      - name: Run Lighthouse Performance Audit
        run: |
          mkdir -p reports
          lighthouse https://fox-one-promptly.ngrok-free.app \
            --output=json \
            --output=html \
            --output-path=reports/lighthouse.html \
            --chrome-flags="--headless"

      - name: Debug - List Files
        run: ls -alh reports

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: reports/lighthouse.html
