version: '3.8'

services:
  gitea:
    image: maias816/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
    ports:
      - "3000:3000"  # Web UI
      - "2222:22"  # SSH access
    volumes:
      - gitea_data:/data
    restart: always

volumes:
  gitea_data:
