version: '3.7'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - "3000:3000"  # Web UI
      - "2222:22"    # SSH
    environment:
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea_user
      - GITEA__database__PASSWD=gitea_pass
    volumes:
      - gitea_data:/data
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: gitea_db
    restart: always
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea_user
      POSTGRES_PASSWORD: gitea_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  gitea_data:
  postgres_data:
