name: Gitea Setup and Testing

on:
  push:
    branches:
      - dev  # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - dev  # Trigger the workflow when a PR is opened to the main branch
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        options: --health-cmd="pg_isready -U gitea_user" --health-timeout=30s --health-retries=3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: gitea
          POSTGRES_USER: gitea_user
          POSTGRES_PASSWORD: gitea_pass

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build Test Docker Image
        run: |
          docker build -t api_ui_tests:latest -f Dockerfile.test .

      - name: Start Gitea & PostgreSQL using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for Gitea to be ready
        run: |
          sleep 20  # Adjust based on how long it takes for Gitea to fully start

      - name: Pull Test Docker Image
        run: |
          docker pull api_ui_tests:latest  # Pull the existing image

      - name: Run API and UI Tests
        run: |
          docker run --rm api_ui_tests:latest  # Run the tests using the image

      - name: Tear down containers
        run: |
          docker-compose down
