name: Gitea CI Workflow

on:
  push:
    branches:
      - dev  # Run when pushing to 'dev'
  pull_request:
    branches:
      - dev  # Run tests when a PR is opened or updated targeting 'dev'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    needs: docker  # Run after the Docker job finishes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull latest Gitea image
        run: docker pull maias816/gitea:latest

      - name: Start Gitea with Docker Compose
        run: docker-compose up -d

      # Wait for Gitea to start
      - name: Wait for Gitea to start
        run: sleep 10  # Adjust time if needed

      # ✅ Clone API tests repository
      - name: Clone API Tests Repository
        run: git clone https://github.com/maias1907/gitea-Automation-Testing-Project.git

      # ✅ Install dependencies (if needed)
      - name: Install API test dependencies
        run: |
          cd gitea-Automation-Testing-Project


      # ✅ Run API tests
      - name: Run API Tests
        run: |
          cd gitea-Automation-Testing-Project
          mvn -q clean test -Dtest=**/APITests/*

      - name: Stop Gitea
        run: docker-compose down
