name: Load Testing with JMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  jmeter:
    name: Run JMeter Tests and Generate HTML Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run JMeter Load Test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/jmeter/gite-test-plan.jmx
          outputReportsFolder: reports/
          args: "-n -t tests/jmeter/gite-test-plan.jmx -l reports/results.jtl -e -o reports/html-report"

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: reports/html-report/
