version: '3.8'

services:
  gitea:
    image: maias816/gitea:latest  # Use the image you built in GitHub Actions
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
    ports:
      - "3000:3000"  # Gitea Web UI
      - "2222:22"  # Gitea SSH access
    volumes:
      - gitea_data:/data  # Persist data so it doesn't get lost after restart
    restart: always

volumes:
  gitea_data:
